name: dev_rzp_getway
description: "This package for razorpay payment getway with automatic order id."
version: 3.0.2
homepage: https://github.com/Developer-ritesh/dev_rzp_getway
repository:  https://github.com/Developer-ritesh/dev_rzp_getway
issue_tracker:  https://github.com/Developer-ritesh/dev_rzp_getway/issues

metadata:
  repository: https://github.com/Developer-ritesh/dev_rzp_getway
  website: https://biharigraphic.com/
  linkedin: https://www.linkedin.com/in/developerritesh/

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  razorpay_flutter: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  
screenshots:
  - description: 'Razorpay Flutter'
    path: doc/razorpay.webp
