name: dev_rzp_getway
description: "This package for razorpay payment getway with automatic order id."
version: 1.0.0

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  razorpay_flutter: ^1.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  

